### ISSUE TITLE
want to understand some details in the paper

### ISSUE THREAD

**Issue by tysonyuu** [bcmi220/seq2seq_parser#1]
Sorry, I want to figure out something after reading the paper.

1. Do you use one-hot encoding to represent the target(…,L2,L1,R1,R2,…)?

2. When applying beam search to decode a sentence, how do you make sure that there just exists exactly one sub-root?(For example, there may be two or no word predicting ROOT as its head). 

Do you regard the sub-root detected by Sub-root Decomposition as the final sub-root regardless of the beam search scores? Since the decomposed sub-sentences must have the same sub-root that they can compose together latter.

Besides, when the sentence length L < the threshold of Sub-root Decomposition, you don’t do Sub-root Decomposition and find the sub-root before decoding.
How do you make sure that there just exists exactly one sub-root when decoding?

**Comment by bcmi220** [comment]
Hello, 1. the target encoding is the same as the NMT model does, it is a embedding.
2. We don't ensure exactly one sub-root, this will not influence the following beam search. The model limit the first or the last position as sub-root when in sub-root mode.
Yes, I regard the sub-root detected by Sub-root Decomposition as the final sub-root regardless of the beam search scores. 
For sentence length L < the threshold when decoding, you have the knowledge for sentence and don't limit the first or last be SUB-ROOT.
I think this will help you.

**Comment by tysonyuu** [comment]
OK. Thank you for your reply.
